import { createTypes } from 'reduxsauce';

export default createTypes(`
  PUSH_NEW_ROUTE
  REPLACE_ROUTE
  REPLACE_OR_PUSH_ROUTE
  POP_ROUTE
  POP_TO_ROUTE
  LOAD_TASKS_REQUEST
  LOAD_TASKS_ERROR
  LOAD_TASKS_SUCCESS
  SET_MAIN_TAB
  SET_SPINNER_VISIBLE

  SET_ALGOLIA_MAIN_PARAMS
  SET_ALGOLIA_MAIN_PROPERTIES
  SET_ALGOLIA_SELECTEDPROPERTY  

  SET_ALGOLIA_SEARCH_PARAMS
  SET_ALGOLIA_SEARCH_COMMUNITIES
  SET_ALGOLIA_SEARCH_PROPERTIES
  SET_ALGOLIA_SEARCH_CITIES
  SET_ALGOLIA_SEARCH_SCHOOLS
  
`);
