import { createTypes } from 'reduxsauce';

export default createTypes(`
  PUSH_NEW_ROUTE
  REPLACE_ROUTE
  REPLACE_OR_PUSH_ROUTE
  POP_ROUTE
  POP_TO_ROUTE
  LOAD_TASKS_REQUEST
  LOAD_TASKS_ERROR
  LOAD_TASKS_SUCCESS
  SET_MAIN_TAB
  SET_SPINNER_VISIBLE
  SET_ALGOLIA_PROPERTIES
  SET_ALGOLIA_COMMUNITIES
  SET_ALGOLIA_SEARCHPARAMS
  SET_ALGOLIA_SELECTEDPROPERTY
`);
